config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations" }

  # Set root link
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root 'welcome#index'

  # set root dashboard link
  get 'dashboard', to: 'dashboard#index'

  resources :meals

  resources :foods

  resources :users

  resources :goals

  resources :recipes

  # Redirect to root_path if no route matches
  match "*path" => redirect("/"), via: [:get, :post]
end

app/controllers/dashboard_controller.rb
require 'rest-client'
class DashboardController < ApplicationController
    before_action :authenticate_user!

    def index
        @today = Date.today
        
        @breakfast = Meal.where(user_id: current_user, date: @today, meal_type: "Breakfast")
        @lunch = Meal.where(user_id: current_user, date: @today, meal_type: "Lunch")
        @dinner = Meal.where(user_id: current_user, date: @today, meal_type: "Dinner")
        @morning_snack = Meal.where(user_id: current_user, date: @today, meal_type: "Morning Snack")
        @afternoon_snack = Meal.where(user_id: current_user, date: @today, meal_type: "Afternoon Snack")
        @evening_snack = Meal.where(user_id: current_user, date: @today, meal_type: "Evening Snack")

        all_nutrients_from_meals

        @total_nutrition = @total_carbohydrates + @total_proteins + @total_fat

        @percent_of_total_carbs =  (@total_carbohydrates.to_f / @total_nutrition.to_f * 100)

        @percent_of_total_proteins = (@total_proteins.to_f / @total_nutrition.to_f * 100)
    
        @percent_of_total_fat = (@total_fat.to_f / @total_nutrition.to_f * 100)

        recommended_nutritions

        # Recommended Recipes

        recommended_recipes
    end

    def all_nutrients_from_meals
        @day = Meal.where(user_id: current_user, date: @today)

        @total_calories = 0
        @total_proteins = 0
        @total_carbohydrates = 0
        @total_fat = 0

        @day.each do |d|
            @total_calories += d.total_calories
            @total_proteins += d.total_proteins
            @total_carbohydrates += d.total_carbohydrates
            @total_fat = d.total_fat
        end
    end

    def recommended_nutritions
        @user = current_user
        @rec_total_calories = @user.recommended_calories_per_day
        @rec_total_carbohydrates = @user.recommended_carbohydrates_per_day
        @rec_total_proteins = @user.recommended_proteins_per_day
        @rec_total_fat = @user.recommended_fat_per_day

        @rec_total_nutrition = @rec_total_carbohydrates + @rec_total_proteins + @rec_total_fat

        @rec_percent_of_total_carbs = ((@rec_total_carbohydrates.to_f / @rec_total_nutrition.to_f * 100 * 1000).round / 1000.00)

        @rec_percent_of_total_proteins = ((@rec_total_proteins.to_f / @rec_total_nutrition.to_f * 100 * 1000).round / 1000.00)

        @rec_percent_of_total_fat = ((@rec_total_fat.to_f / @rec_total_nutrition.to_f * 100 * 1000).round / 1000.00)
    end

    def get_recommended_recipes
        response = RestClient.get("https://spoonacular-recipe-food-nutrition-v1.p.mashape.com/recipes/mealplans/generate?targetCalories=" + current_user.recommended_calories_per_day.to_s + "&timeFrame=day", headers={"X-Mashape-Key" => "agqlHIpiaOmsheRZvwYn20FulAyPp1MHH3PjsnIgR2lAenL75z",
            "Accept" => "application/json"})
        
        @parsedResponse = JSON.parse(response)
        @recRecipes = @parsedResponse['meals']

        @recRecipesNutrients = @parsedResponse['nutrients']
        @totalCalories = @recRecipesNutrients['calories'].to_f
        @totalProteins = @recRecipesNutrients['protein'].to_f
        @totalFat = @recRecipesNutrients['fat'].to_f
        @totalCarbohydrates = @recRecipesNutrients['carbohydrates'].to_f
    end

    def recommended_recipes
        @today = Date.today

        if user_signed_in?
        
        @queryRecipe = RecommendedRecipe.where(user_id: current_user.id, day: @today)
        
            if @queryRecipe.blank?
                get_recommended_recipes

                @newRecRecipe = RecommendedRecipe.create(meals_response: @recRecipes.to_json, total_calories: @totalCalories, total_proteins: @totalProteins, total_fat: @totalFat, total_carbohydrates: @totalCarbohydrates, day: @today, user_id: current_user.id)

                @newRecRecipe.save

                redirect_to(dashboard_path)
            
            else
                @recipeMeals = JSON.parse(@queryRecipe[0].meals_response)

                @recipeTotalCalories = @queryRecipe[0].total_calories
                @recipeTotalCarbs = @queryRecipe[0].total_carbohydrates
                @recipeTotalProteins = @queryRecipe[0].total_proteins
                @recipeTotalFat = @queryRecipe[0].total_fat

                if @queryRecipe[0].day != @today
                    get_recommended_recipes
                    @recRecipe.update(meals_response: @recRecipes, total_calories: @totalCalories, total_proteins: @totalProteins, total_fat: @totalFat, total_carbohydrates: @totalCarbohydrates, day: @today)
                end
            end
        end
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_meals.html.erb
<div id="meals">
    <div class="wrapper-600">
        <h2 class="section-title">Meals</h2>
        <p class="section-moto"><%= Date.today.strftime("%A, %B %d, %Y") %></p>

        <div id="meals-holder">
            <div class="holder">
                <% unless @breakfast.blank? %>
                    <% @breakfast.each do |f| %>
                        <a href="<%= meal_path(f.id) %>">
                            <div class="circle active">
                                <p>
                                    <%= f.total_calories.round %><br>
                                    <span>Cal</span>
                                </p>
                            </div>
                        </a>
                    <% end %>
                <% else %>
                    <a href="<%= new_meal_path(:meal_type => "Breakfast") %>">
                        <div class="circle">
                            <p>+</p>
                        </div>
                    </a>
                <% end %>
                <p>Breakfast</p>
            </div>

            <div class="holder">
                <% unless @lunch.blank? %>
                    <% @lunch.each do |f| %>
                        <a href="<%= meal_path(f.id) %>">
                            <div class="circle active">
                                <p>
                                    <%= f.total_calories.round %><br>
                                    <span>Cal</span>
                                </p>
                            </div>
                        </a>
                    <% end %>
                <% else %>
                    <a href="<%= new_meal_path(:meal_type => "Lunch") %>">
                        <div class="circle">
                            <p>+</p>
                        </div>
                    </a>
                <% end %>
                <p>Lunch</p>
            </div>

            <div class="holder">
                <% unless @dinner.blank? %>
                    <% @dinner.each do |f| %>
                        <a href="<%= meal_path(f.id) %>">
                            <div class="circle active">
                                <p>
                                    <%= f.total_calories.round %><br>
                                    <span>Cal</span>
                                </p>
                            </div>
                        </a>
                    <% end %>
                <% else %>
                    <a href="<%= new_meal_path(:meal_type => "Dinner") %>">
                        <div class="circle">
                            <p>+</p>
                        </div>
                    </a>
                <% end %>
                <p>Dinner</p>
            </div>

            <div class="holder">
                <% unless @morning_snack.blank? %>
                    <% @morning_snack.each do |f| %>
                        <a href="<%= meal_path(f.id) %>">
                            <div class="circle active">
                                <p>
                                    <%= f.total_calories.round %><br>
                                    <span>Cal</span>
                                </p>
                            </div>
                        </a>
                    <% end %>
                <% else %>
                    <a href="<%= new_meal_path(:meal_type => "Morning Snack") %>">
                        <div class="circle">
                            <p>+</p>
                        </div>
                    </a>
                <% end %>
                <p>Morning Snack</p>
            </div>

            <div class="holder">
                <% unless @afternoon_snack.blank? %>
                    <% @afternoon_snack.each do |f| %>
                        <a href="<%= meal_path(f.id) %>">
                            <div class="circle active">
                                <p>
                                    <%= f.total_calories.round %><br>
                                    <span>Cal</span>
                                </p>
                            </div>
                        </a>
                    <% end %>
                <% else %>
                    <a href="<%= new_meal_path(:meal_type => "Afternoon Snack") %>">
                        <div class="circle">
                            <p>+</p>
                        </div>
                    </a>
                <% end %>
                <p>Afternoon Snack</p>
            </div>

            <div class="holder">
                <% unless @evening_snack.blank? %>
                    <% @evening_snack.each do |f| %>
                        <a href="<%= meal_path(f.id) %>">
                            <div class="circle active">
                                <p>
                                    <%= f.total_calories.round %><br>
                                    <span>Cal</span>
                                </p>
                            </div>
                        </a>
                    <% end %>
                <% else %>
                    <a href="<%= new_meal_path(:meal_type => "Evening Snack") %>">
                        <div class="circle">
                            <p>+</p>
                        </div>
                    </a>
                <% end %>
                <p>Evening <br> Snack</p>
            </div>
        </div>
    </div>
</div>

app/views/dashboard/_recipes.html.erb
<div class="wave recipes"></div>

<div id="recipes">
    <div class="wrapper-600">
        <h2 class="section-title">Recommended Recipes</h2>
        <p class="section-moto"><%= Date.today.strftime("%A, %B %d, %Y") %></p>

    </div>
    <div class="wrapper-800">
        <div id="recipes-holder">
            <% @recipeMeals.each do |recipe| %>
                <div class="recipe">
                    <div class="recipe-image" style="background-image: url('https://spoonacular.com/recipeImages/<%= recipe['image'] %>')">
                    </div>
                    <div class="recipe-info">
                        <h3><%= recipe['title'] %></h3>
                        <p><span>Ready in:</span> <%= recipe['readyInMinutes'] %> minutes</p>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="keys">
            <div class="key">
                <div class="color calories"></div>
                <p>Calories: <%= @recipeTotalCalories %>
            </div>
            <div class="key">
                <div class="color carbs"></div>
                <p>Carbs <%= @recipeTotalCarbs %> g</p>
            </div>
            <div class="key">
                <div class="color proteins"></div>
                <p>Proteins <%= @recipeTotalProteins %> g</p>
            </div>
            <div class="key">
                <div class="color fat"></div>
                <p>Fat <%= @recipeTotalFat %> g</p>
            </div>
        </div>
    </div>
</div>

app/views/dashboard/_statistics.html.erb
<div class="wave statistics"></div>

<div id="statistics">
    <div class="wrapper-600">
        <h2 class="section-title">Statistics</h2>
        <p class="section-moto"><%= Date.today.strftime("%A, %B %d, %Y") %></p>

        <p class="progress-bar-title">Recommended intake</p>
        <div class="progress-bar">
            <div class="progress carbs" style="width: <%= @rec_percent_of_total_carbs %>%"></div><div class="progress proteins" style="width: <%= @rec_percent_of_total_proteins %>%"></div><div class="progress fat" style="width: <%= @rec_percent_of_total_fat %>%"></div>
        </div>
        <div class="progress-bar-label">
            <div class="carbs" style="width: 33.33333%">
                <p><%= @rec_percent_of_total_carbs.round(1) %>%</p>
            </div><div class="proteins" style="width: 33.33333%">
                <p><%= @rec_percent_of_total_proteins.round(1) %>%</p>
            </div><div class="fat" style="width: 33.33333%">
                <p><%= @rec_percent_of_total_fat.round(1) %>%</p>
            </div>
        </div>

        <div class="keys">
            <div class="key">
                <div class="color carbs"></div>
                <p>Carbs <%= @rec_total_carbohydrates %> g</p>
            </div>
            <div class="key">
                <div class="color proteins"></div>
                <p>Proteins <%= @rec_total_proteins %> g</p>
            </div>
            <div class="key">
                <div class="color fat"></div>
                <p>Fat <%= @rec_total_fat %> g</p>
            </div>
        </div>

        <br>
        <br>

        <p class="progress-bar-title">Actual intake</p>
        <div class="progress-bar">
            <div class="progress carbs" style="width: <%= @percent_of_total_carbs %>%"></div><div class="progress proteins" style="width: <%= @percent_of_total_proteins %>%"></div><div class="progress fat" style="width: <%= @percent_of_total_fat %>%"></div>
        </div>
        <div class="progress-bar-label">
            <div class="carbs" style="width: 33.33333%">
                <p><%= if @percent_of_total_carbs >= 0 then  @percent_of_total_carbs.round(1) else  "No Data" end %>%</p>
            </div><div class="proteins" style="width: 33.33333%">
                <p><%= if @percent_of_total_proteins >= 0 then @percent_of_total_proteins.round(1) else "No Data" end %>%</p>
            </div><div class="fat" style="width: 33.33333%">
                <p><%= if @percent_of_total_fat >= 0 then @percent_of_total_fat.round(1) else "No Data" end %>%</p>
            </div>
        </div>

        <div class="keys">
            <div class="key">
                <div class="color carbs"></div>
                <p>Carbs <%= @total_carbohydrates %> g</p>
            </div>
            <div class="key">
                <div class="color proteins"></div>
                <p>Proteins <%= @total_proteins %> g</p>
            </div>
            <div class="key">
                <div class="color fat"></div>
                <p>Fat <%= @total_fat %> g</p>
            </div>
        </div>

        <div id="total-calories">
            <h2><%= @total_calories %> <span>Cal</span></h2>
            <p>/ <%= @rec_total_calories %> <br> Recommended daily calories</p>
        </div>

        <div id="breakdown">
            <% unless @breakfast.empty? %>
                <p class="label">Breakfast</p>
                <% @breakfast.each do |f| %>
                    <div class="row clearfix">
                        <p class="count"><%= f.total_calories %> Cal</p>
                        <a href="<%= meal_path(f.id) %>" class="edit">Edit Meal</a>
                    </div>
                <% end %>
            <% end %>

            <% unless @lunch.empty? %>
                <p class="label">Lunch</p>
                <% @lunch.each do |f| %>
                    <div class="row clearfix">
                        <p class="count"><%= f.total_calories %> Cal</p>
                        <a href="<%= meal_path(f.id) %>" class="edit">Edit Meal</a>
                    </div>
                <% end %>
            <% end %>

            <% unless @dinner.empty? %>
                <p class="label">Dinner</p>
                <% @dinner.each do |f| %>
                    <div class="row clearfix">
                        <p class="count"><%= f.total_calories %> Cal</p>
                        <a href="<%= meal_path(f.id) %>" class="edit">Edit Meal</a>
                    </div>
                <% end %>
            <% end %>

            <% unless @morning_snack.empty? %>
                <p class="label">Morning Snack</p>
                <% @morning_snack.each do |f| %>
                    <div class="row clearfix">
                        <p class="count"><%= f.total_calories %> Cal</p>
                        <a href="<%= meal_path(f.id) %>" class="edit">Edit Meal</a>
                    </div>
                <% end %>
            <% end %>

            <% unless @afternoon_snack.empty? %>
                <p class="label">Afternoon Snack</p>
                <% @afternoon_snack.each do |f| %>
                    <div class="row clearfix">
                        <p class="count"><%= f.total_calories %> Cal</p>
                        <a href="<%= meal_path(f.id) %>" class="edit">Edit Meal</a>
                    </div>
                <% end %>
            <% end %>

            <% unless @evening_snack.empty? %>
                <p class="label">Evening Snack</p>
                <% @evening_snack.each do |f| %>
                    <div class="row clearfix">
                        <p class="count"><%= f.total_calories %> Cal</p>
                        <a href="<%= meal_path(f.id) %>" class="edit">Edit Meal</a>
                    </div>
                <% end %>
            <% end %>
        </div>

        <a href="<%= new_meal_path %>" id="add-meal">
            <div id="add-meal">
                <p>Add Meal</p>
            </div>
        </a>
    </div>
</div>

app/views/dashboard/_trends.html.erb
<div class="wave trends"></div>

<div id="trends">
    <div class="wrapper-600">
        <h2 class="section-title">Trends</h2>
        <p class="section-moto"><%= (Date.today - 1.month).strftime("%B %d, %Y") %> - <%= Date.today.strftime("%B %d, %Y") %></p>

        <%= line_chart [
            {name: "Calories", data: Meal.where(user_id: current_user, :date => (Date.today - 1.month)..(Date.today)).group_by_day(:date).sum(:total_calories)},
            {name: "Carbohydrates", data: Meal.where(user_id: current_user, :date => (Date.today - 1.month)..(Date.today)).group_by_day(:date).sum(:total_carbohydrates)},
            {name: "Proteins", data: Meal.where(user_id: current_user, :date => (Date.today - 1.month)..(Date.today)).group_by_day(:date).sum(:total_proteins)},
            {name: "Fat", data: Meal.where(user_id: current_user, :date => (Date.today - 1.month)..(Date.today)).group_by_day(:date).sum(:total_fat)},
        ], download: true %>
    </div>
</div>

app/views/dashboard/index.html.erb
<% content_for :banner do %>
    Dashboard
<% end %>
    
<% content_for :dashboard_page_body do %>
    <%= render 'meals' %>

    <%= render 'statistics' %>

    <%= render 'trends' %>

    <%= render 'recipes'%>
<% end %>