config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations" }

  # Set root link
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root 'welcome#index'

  # set root dashboard link
  get 'dashboard', to: 'dashboard#index'

  resources :meals

  resources :foods

  resources :users

  resources :goals

  resources :recipes

  # Redirect to root_path if no route matches
  match "*path" => redirect("/"), via: [:get, :post]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/direction.rb
class Direction < ApplicationRecord
  belongs_to :recipe
end

app/models/food.rb
class Food < ApplicationRecord
    has_many :meal_foods
    has_many :meals, through: :meal_foods
end

app/models/goal.rb
class Goal < ApplicationRecord
    belongs_to :user, optional: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :user, optional: true
    has_many :meal_foods, dependent: :destroy
    has_many :foods, through: :meal_foods

    # Calculate database columns

    def calc_total_calories
        self.total_calories = self.foods.sum(:calories)
    end

    def calc_total_carbohydrates
        self.total_carbohydrates = self.foods.sum(:carbohydrates)
    end

    def calc_total_proteins
        self.total_proteins = self.foods.sum(:proteins)
    end

    def calc_total_fat
        self.total_fat = self.foods.sum(:fat)
    end

    # Calculate percentages of each nutrition 

    def calc_total_nutrition
        return self.total_carbohydrates + self.total_proteins + self.total_fat
    end

    def calc_percent_of_total_carbs
        return (self.total_carbohydrates.to_f / self.calc_total_nutrition.to_f * 100)
    end

    def calc_percent_of_total_proteins
        return (self.total_proteins.to_f / self.calc_total_nutrition.to_f * 100)
    end

    def calc_percent_of_total_fat
        return (self.total_fat.to_f / self.calc_total_nutrition.to_f * 100)
    end
end

app/models/meal_food.rb
class MealFood < ApplicationRecord
  belongs_to :meal
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :ingredients, dependent: :destroy
    has_many :directions, dependent: :destroy

    accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
    accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

    validates :title, :description, :image, presence: true

    # Paperclip
    has_attached_file :image, styles: { medium: "600x600>"}
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    # Search recipes method
    def self.search(search)
        if search
            where('title LIKE ?', "%#{search.capitalize}")
        else
            all.order("created_at DESC")
        end
    end
end

app/models/recommended_recipe.rb
class RecommendedRecipe < ApplicationRecord
    belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable

    has_many :meals, dependent: :destroy
    has_one :goal, dependent: :destroy
    has_one :recommended_recipe, dependent: :destroy

    def calc_recommended_nutrients_per_day
        @user = self

        # Calc recommended calories per day
        if @user.sex == "Male"
            @recommended_calories_per_day = 66 + (13.7 * @user.weight) + (5 * @user.height) - (6.8 * @user.age).round(1)

        elsif @user.sex == "Female"
            @recommended_calories_per_day = 655 + (9.6 * @user.weight) + (1.8 * @user.height) - (4.7 * @user.age).round(1)
        end

        # Calc recommended proteins, carbohydrates per day
        if @user.age <= 20
            @recommended_proteins_per_day = (0.7 - (1 * @user.weight * 1000 / 453.592)).abs.round(1)

            @recommended_carbohydrates_per_day = (2.2 - (3.2 * @user.weight * 1000 / 453.592)).abs.round(1)

            @recommended_fat_per_day = (0.25 - (0.4 * @user.weight * 1000 / 453.592)).abs.round(1)

        elsif @user.age >= 21 && @user.age <= 40
            @recommended_proteins_per_day = (0.9 - (1.2 * @user.weight * 1000 / 453.592)).abs.round(1)

            @recommended_carbohydrates_per_day = (1.7 - (2.7 * @user.weight * 1000 / 453.592)).abs.round(1)

            @recommended_fat_per_day = (0.35 - (0.5 * @user.weight * 1000 / 453.592)).abs.round(1)

        elsif @user.age >= 41 && @user.age <= 65
            @recommended_proteins_per_day = (1.1 - (1.4 * @user.weight * 1000 / 453.592)).abs.round(1)

            @recommended_carbohydrates_per_day = (1.2 - (2.2 * @user.weight * 1000 / 453.592)).abs.round(1)

            @recommended_fat_per_day = (0.45 - (0.6 * @user.weight * 1000 / 453.592)).abs.round(1)

        elsif @user.age > 65
            @recommended_proteins_per_day = (1.3 - (1.5 * @user.weight * 1000 / 453.592)).abs.round(1)

            @recommended_carbohydrates_per_day = (0.7 - (1.7 * @user.weight * 1000 / 453.592)).abs.round(1)

            @recommended_fat_per_day = (0.55 - (0.7 * @user.weight * 1000 / 453.592)).abs.round(1)
        end

        @user.update(recommended_calories_per_day: @recommended_calories_per_day, recommended_proteins_per_day: @recommended_proteins_per_day, recommended_carbohydrates_per_day: @recommended_carbohydrates_per_day, recommended_fat_per_day: @recommended_fat_per_day)

        return @recommended_carbohydrates_per_day
    end

    def calc_total_nutrition
        return self.total_carbohydrates + self.total_proteins + self.total_fat
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/welcome/index.html.erb
    <div id="background">
        <div id="background-darken">
            <header class="clearfix">
                <div class="wrapper-wide">
                    <%= link_to 'EAT HEALTHIER', root_path, id: 'logo' %>
                    <nav>
                        <ul>
                            <% unless user_signed_in? %>
                                <li>
                                    <%= link_to 'Sign In', new_user_session_path %>
                                </li><li>
                                    <a href="#">About</a>
                                </li><li>
                                    <%= link_to 'Recipes', recipes_path%>
                                </li>
                            <% else %>
                                <li>
                                    <%= link_to 'Dashboard', dashboard_path %>
                                </li><li>
                                    <%= link_to 'My Profile', user_path(current_user) %>
                                </li><li>
                                    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
                                </li>
                            <% end %>
                        </ul>
                    </nav>
                </div>
            </header>
            <div class="wrapper-wide">
                <h1>
                    Eat to fuel your body, not
                    <br>
                    to feed your emotions.
                </h1>
                <%= link_to 'Sign Up', new_user_registration_path, class: "button button-highlight" %>
                <%= link_to 'Sign In', new_user_session_path, class: "button button-white" %>
            </div>
        </div>
    </div>