config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations" }

  # Set root link
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root 'welcome#index'

  # set root dashboard link
  get 'dashboard', to: 'dashboard#index'

  resources :meals

  resources :foods

  resources :users

  resources :goals

  resources :recipes

  # Redirect to root_path if no route matches
  match "*path" => redirect("/"), via: [:get, :post]
end

app/models/meal.rb
class Meal < ApplicationRecord
    belongs_to :user, optional: true
    has_many :meal_foods, dependent: :destroy
    has_many :foods, through: :meal_foods

    # Calculate database columns

    def calc_total_calories
        self.total_calories = self.foods.sum(:calories)
    end

    def calc_total_carbohydrates
        self.total_carbohydrates = self.foods.sum(:carbohydrates)
    end

    def calc_total_proteins
        self.total_proteins = self.foods.sum(:proteins)
    end

    def calc_total_fat
        self.total_fat = self.foods.sum(:fat)
    end

    # Calculate percentages of each nutrition 

    def calc_total_nutrition
        return self.total_carbohydrates + self.total_proteins + self.total_fat
    end

    def calc_percent_of_total_carbs
        return (self.total_carbohydrates.to_f / self.calc_total_nutrition.to_f * 100)
    end

    def calc_percent_of_total_proteins
        return (self.total_proteins.to_f / self.calc_total_nutrition.to_f * 100)
    end

    def calc_percent_of_total_fat
        return (self.total_fat.to_f / self.calc_total_nutrition.to_f * 100)
    end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
    before_action :authenticate_user!
    before_action :find_meal, only: [:show, :edit, :update, :destroy]

    def index
    end

    def new
        @meal = Meal.new
    end

    def create
        @meal = current_user.meals.new(meal_params)
        

        if @meal.save
            @today = Date.today

            @meal.update(total_calories: @meal.calc_total_calories, total_carbohydrates:    @meal.calc_total_carbohydrates, total_proteins: @meal.calc_total_proteins, total_fat: @meal.calc_total_fat, date: @today)


            redirect_to @meal, notice: "Successfully created meal."
        else
            render 'new'
        end
    end

    def show
    end

    def edit
        @meal_foods = @meal.meal_foods.includes(:food)
    end

    def update
        if @meal.update(meal_params)
            @meal.update(total_calories: @meal.calc_total_calories, total_carbohydrates:    @meal.calc_total_carbohydrates, total_proteins: @meal.calc_total_proteins, total_fat: @meal.calc_total_fat)

            redirect_to @meal, notice: "Successfully updated meal."
        else
            render 'edit'
        end
    end

    def destroy
        @meal.destroy
        redirect_to root_path, notice: "Successfully deleted meal."
    end

    private

    def find_meal
        @meal = Meal.where(user_id: current_user).find(params[:id])
    end

    def meal_params
        params.require(:meal).permit!
        # .permit(:user_id, :meal_type, :date, :total_calories, :total_carbohydrates, :total_fat, food_ids:[])
    end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_meals_js.html.erb
<script>
    $(document).ready(function() {
        $(document).on('click', '.add-food', function() {
            var partial = "<%= escape_javascript(render partial: 'new_field') %>"

            $(partial).insertBefore(".submit");
            
            $('select.search-meals').select2({
                placeholder: "Select a meal"
            });
        })
        
        $(document).on('click', '.delete-food', function() {
            $(this).parent().parent().parent().remove();
        })

        $('select.search-meals').select2({
            placeholder: "Select a meal"
        });
    })
</script>

app/views/meals/_new_field.html.erb
<div class="field">
    <label class="input-dropdown">Food Item</label>
    <%= select_tag "meal[food_ids][]", options_from_collection_for_select(Food.all, "id", "name"), include_blank: true, class: "search-meals", data: {placeholder: "Select a food item"} %>

    <ul class="sub-buttons">
        <li>
            <a href="javascript:void(0)" class="add-food">Add Food Item</a>
        </li><li>
            <a href="javascript:void(0)" class="delete-food">Delete Food Item</a>
        </li>
    </ul>
</div>

app/views/meals/edit.html.erb
<% content_for :exclusive_javascript do %>meals<% end %>
<% content_for :banner do %>Meals<% end %>
<% content_for :section_title do %>Edit Meal<% end %>

<% content_for :dashboard_page_body do %>
<div id="add-meal">
    <h2 class="section-title"><%= yield(:section_title) %></h2>
    <p class="section-moto"><%= @meal.date.strftime("%A, %B %d, %Y") %></p>

    <div id="form" class="new-meal">
        <div class="wrapper-600">
            <%= form_for(@meal) do |f| %>
                <div class="field">
                    <%= f.label :meal_type %>
                    <%= f.select :meal_type, ["Breakfast", "Lunch", "Dinner", "Morning Snack", "Afternoon Snack", "Evening Snack"] %>
                </div>

                <% @meal_foods.each do |mf| %>
                    <div class="field">
                        <label class="input-dropdown">Food Item</label>
                        <%= select_tag "meal[food_ids][]", options_from_collection_for_select(Food.where(id: mf.food_id), "id", "name"), include_blank: false, class: "search-meals" %>

                        <ul class="sub-buttons">
                            <li>
                                <a href="javascript:void(0)" class="add-food">Add Food Item</a>
                            </li><li>
                                <a href="javascript:void(0)" class="delete-food">Delete Food Item</a>
                            </li>
                        </ul>
                    </div>
                <% end %>

                <div class="field submit">
                    <%= f.submit class: "button button-highlight button-block" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

<% end %>
<%= render 'meals_js' %>

app/views/meals/new.html.erb
<% content_for :exclusive_javascript do %>meals<% end %>
<% content_for :banner do %>Meals<% end %>
<% content_for :section_title do %>Add Meal<% end %>

<% content_for :dashboard_page_body do %>
<div id="add-meal">
    <h2 class="section-title"><%= yield(:section_title) %></h2>
    <p class="section-moto"><%= Date.today.strftime("%A, %B %d, %Y") %></p>

    <div id="form" class="new-meal">
        <div class="wrapper-600">
            <%= form_for(@meal) do |f| %>
                <div class="field">
                    <%= f.label :meal_type %>
                    <% if params.has_key?(:meal_type) %>
                        <%= f.select :meal_type, options_for_select([params[:meal_type]]) %>
                    <% else %>
                        <%
                            @user = current_user
                            @today = Date.today

                            @mealBreakfast = Meal.where(meal_type: 'Breakfast', user_id: current_user, date: @today)
                            @mealLunch = Meal.where(meal_type: 'Lunch', user_id: current_user, date: @today)
                            @mealDinner = Meal.where(meal_type: 'Dinner', user_id: current_user, date: @today)
                            @mealMorningSnack = Meal.where(meal_type: 'Morning Snack', user_id: current_user, date: @today)
                            @mealAfternoonSnack = Meal.where(meal_type: 'Afternoon Snack', user_id: current_user, date: @today)
                            @mealEveningSnack = Meal.where(meal_type: 'Evening Snack', user_id: current_user, date: @today)

                            @currentMeals = []

                            if @mealBreakfast.empty?
                                @currentMeals.push("Breakfast")
                            end

                            if @mealLunch.empty?
                                @currentMeals.push("Lunch")
                            end

                            if @mealDinner.empty?
                                @currentMeals.push("Dinner")
                            end

                            if @mealMorningSnack.empty?
                                @currentMeals.push("Morning Snack")
                            end

                            if @mealAfternoonSnack.empty?
                                @currentMeals.push("Afternoon Snack")
                            end

                            if @mealEveningSnack.empty?
                                @currentMeals.push("Evening Snack")
                            end
                        %>

                        <%= f.select :meal_type, @currentMeals %>
                    <% end %>

                </div>

                <div class="field">
                    <label class="input-dropdown">Food Item</label>
                    <%= select_tag "meal[food_ids][]", options_from_collection_for_select(Food.all, "id", "name"), include_blank: true, class: "search-meals", data: {placeholder: "Select a food item"} %>

                    <ul class="sub-buttons">
                        <li>
                            <a href="javascript:void(0)" class="add-food">Add Food Item</a>
                        </li>
                    </ul>
                </div>

                <div class="field submit">
                    <%= f.submit class: "button button-highlight button-block" %>
                </div>
            <% end %>
        </div>
    </div>
</div>

<% end %>
<%= render 'meals_js' %>

app/views/meals/show.html.erb
<% content_for :banner do %>Meals<% end %>

<% content_for :dashboard_page_body do %>
<div id="add-meal">
    <h2 class="section-title">Meal Statistics</h2>
    <p class="section-moto"><%= @meal.date.strftime("%A, %B %d, %Y") %></p>

    <div id="form" class="new-meal" style="padding-bottom: 0; margin-bottom: 60px">
        <div class="wrapper-600">
            <div class="field">
            <label>Meal Type</label>
            <input type="text" value="<%= @meal.meal_type %>" disabled>
            </div>
        </div>
    </div>

    <div id="statistics" style="background-color: white; padding-top: 0">
        <div class="wrapper-600">
            <p class="progress-bar-title">Intake</p>
            <div class="progress-bar">
                <div class="progress carbs" style="width: <%= @meal.calc_percent_of_total_carbs %>%"></div><div class="progress proteins" style="width: <%= @meal.calc_percent_of_total_proteins %>%"></div><div class="progress fat" style="width: <%= @meal.calc_percent_of_total_fat %>%"></div>
            </div>
            <div class="progress-bar-label">
                <div class="carbs" style="width: 33.33333%">
                    <p><%= @meal.calc_percent_of_total_carbs.round(1)  %>%</p>
                </div><div class="proteins" style="width: 33.33333%">
                    <p><%= @meal.calc_percent_of_total_proteins.round(1) %>%</p>
                </div><div class="fat" style="width: 33.33333%">
                    <p><%= @meal.calc_percent_of_total_fat.round(1) %>%</p>
                </div>
            </div>

            <div class="keys">  
                <div class="key">
                    <div class="color carbs"></div>
                    <p>Carbs <%= @meal.total_carbohydrates %> g</p>
                </div>
                <div class="key">
                    <div class="color proteins"></div>
                    <p>Proteins <%= @meal.total_proteins %> g</p>
                </div>
                <div class="key">
                    <div class="color fat"></div>
                    <p>Fat <%= @meal.total_fat %> g</p>
                </div>
            </div>

            <div id="total-calories">
                <h2>Total: <%= @meal.total_calories.round %> <span>Calories</span></h2>
            </div>

            <div id="breakdown">
                <% @meal.foods.each do |food| %>
                    <p class="label"><%= food.name %></p>
                    <div class="row clearfix">
                        <p class="count"><%= food.calories.round %> Cal</p>
                        <a href="#" class="edit">Edit Food Item</a>
                    </div>
                <% end %>
            </div>

            <div id="delete-edit-meal">
                <div id="delete-meal">
                    <%= link_to "Delete Meal", meal_path(@meal), method: :delete, data: {confirm: "Are you sure?"} %>
                </div><div id="edit-meal">
                    <%= link_to "Edit Meal", edit_meal_path %>
                </div>
            </div>

            <div id="back-button-field">
                <%= link_to "Back to dashboard", dashboard_path, class: "back-button" %>
            </div>
        </div>
    </div>
</div>
<% end %>