config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "registrations" }

  # Set root link
  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root 'welcome#index'

  # set root dashboard link
  get 'dashboard', to: 'dashboard#index'

  resources :meals

  resources :foods

  resources :users

  resources :goals

  resources :recipes

  # Redirect to root_path if no route matches
  match "*path" => redirect("/"), via: [:get, :post]
end

app/models/goal.rb
class Goal < ApplicationRecord
    belongs_to :user, optional: true
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
	before_action :authenticate_user!
	before_action :find_goal, only: [:show, :edit, :update, :destroy]

	def index
  	end

	def new
		@check = Goal.where(user_id: current_user)

		unless @check.empty?
			redirect_to dashboard_path
		else
			@goal = Goal.new
		end
  	end

	def create
		@goal = current_user.build_goal(goal_params)

		if @goal.save
			update_carbs
			redirect_to dashboard_path
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end
	
    def update
        if @goal.update(goal_params)
			update_carbs
            redirect_to dashboard_path
        else
            render 'edit'
        end
	end

	def destroy
		@goal.destroy
		current_user.calc_recommended_nutrients_per_day
        redirect_to dashboard_path
	end
	
	
	private

	def find_goal
		@goal = Goal.where(user_id: current_user).find(params[:id])
    end

	def goal_params
		params.require(:goal).permit(:user_id, :goal_type)
	end

	def update_carbs
		@user = current_user

		if @goal.goal_type == "Lose weight"
			@recommended_carbohydrates_per_day = @user.calc_recommended_nutrients_per_day - (0.2 * @user.calc_recommended_nutrients_per_day).round(1)
		elsif @goal.goal_type == "Gain weight"
			@recommended_carbohydrates_per_day = @user.calc_recommended_nutrients_per_day + (0.25 * @user.calc_recommended_nutrients_per_day).round(1)
		else
			@recommended_carbohydrates_per_day = @user.calc_recommended_nutrients_per_day.round(1)
		end

		@user.update(recommended_carbohydrates_per_day: @recommended_carbohydrates_per_day)
	end
end

app/helpers/goal_helper.rb
module GoalHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/edit.html.erb
<% content_for :banner do %>Goal<% end %>

<% content_for :dashboard_page_body do %>
<div id="add-meal">
    <h2 class="section-title">Edit Goal</h2>
    <p class="section-moto">Choose what your goal is</p>

    <div id="form" class="new-meal">
        <div class="wrapper-600">
            <%= form_for(@goal) do |f| %>
                <div class="field">
                    <%= f.label :goal_type, "You would like to..." %>
                    <%= f.select :goal_type, ["Lose weight", "Gain weight", "Keep current weight"] %>
                </div>
                <div class="field submit">
                    <%= f.submit "Submit", class: "button button-highlight button-block" %>
                </div>
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/goals/new.html.erb
<% content_for :banner do %>Goal<% end %>

<% content_for :dashboard_page_body do %>
<div id="add-meal">
    <h2 class="section-title">Set Goal</h2>
    <p class="section-moto">Choose what your goal is</p>

    <div id="form" class="new-meal">
        <div class="wrapper-600">
            <%= form_for(@goal) do |f| %>
                <div class="field">
                    <%= f.label :goal_type, "Would you like to..." %>
                    <%= f.select :goal_type, ["Lose weight", "Gain weight", "Keep current weight"] %>
                </div>
                <div class="field submit">
                    <%= f.submit "Submit", class: "button button-highlight button-block" %>
                </div>
            <% end %>
        </div>
    </div>
</div>
<% end %>

app/views/goals/show.html.erb
<% content_for :banner do %>Goal<% end %>

<% content_for :dashboard_page_body do %>
<div id="edit-goal">
    <h2 class="section-title">Your Goal</h2>

    <div id="form" class="new-meal" style="padding-bottom: 0; margin-bottom: 60px">
        <div class="wrapper-600">
            <div class="field" style="margin-top: 45px;">
                <%= form_for @goal do |f| %>
                    <%= f.label :goal_type, "You want to..." %>
                    <%= f.text_field :goal_type, disabled: true %>
                <% end %>
            </div>
            <div class="field">
                <%= link_to 'Edit Goal', edit_goal_path, class: "cancel-account-button" %>
                <%= link_to "Delete Goal", goal_path(@goal), method: :delete, data: {confirm: "Are you sure?"}, class: "cancel-account-button" %>
            </div>
        </div>
    </div>
</div>
<% end %>